### ISSUE TITLE
Unable to checkout master src code on Windows

### ISSUE THREAD

**Issue by waikitphoon** [dancamdev/UIs#3]
Hi dancamdev,

I have tried to checkout your code to my local in Windows, and it seems that Im facing this error.

![image](https://user-images.githubusercontent.com/43614605/131438984-445f3530-ccf5-4097-aaf6-b54cc6b55507.png)

This could be due to the newly added folder : Movie Carousel App UI
had a space and the end of the folder name hence causing issues in Windows.

![image](https://user-images.githubusercontent.com/43614605/131438961-2154b8b4-46ac-4c25-bf9e-5aae592a06ce.png)

Appreciate if you could try reformating the folder name.

Thanks!

**Comment by dancamdev** [comment]
Hi, yes, I can totally do that

**Comment by waikitphoon** [comment]
Thanks @dancamdev !

**Comment by dancamdev** [comment]
This should now be fixed! Enjoy!
